### PR TITLE
Upgrade zebra to after factsetid changes

### PR DESCRIPTION
**Pull request by tranma**
I think I can just savage the version number for the zebra cli test. But I'm getting different results:

```
-ID00000001|2.2|1|c
+ID00000001|2.2|1|
```

not really sure why yet.

### CODE REVIEW

**Comment by tranma** [comment]
I think perhaps the new zebra exposed a bug in the zebra reading here in icicle. Sparse output:

```
$ diff old new
< ID00000001|test_attribute|c
---
> ID00000001|test_attribute|
```

**Comment by tranma** [comment]
oh, never mind. I forgot new zebra includes the prefix sum scan changes. Fixed.

**Comment by jystic** [comment]
Nice 👍

**Comment by amosr** [comment]
> oh, never mind. I forgot new zebra includes the prefix sum scan changes. Fixed.

doh, sorry. I closed that PR after I saw that you had implemented that in your other PR

👍

**Pull request merged**
