### PR TITLE
tolower attribute names so they can be used as var names

### PR DESCRIPTION
**Pull request by tranma**
a hack for https://github.com/ambiata/icicle/issues/263

### CODE REVIEW

**Comment by tranma** [comment]
hungarian notation is an option, is it better? 😅

**Comment by amosr** [comment]
Need to modify the Source parser too, so it can parse "feature ALL_CAPS": at the moment this is tokenised to [KeywordFeature, Constructor "ALL_CAPS"]. best to just modify feature parser to accept variables or constructors

**Comment by amosr** [comment]
right - I guess it isn't necessary, but I think it'd be ideal

**Comment by tranma** [comment]
uh, is that a lexer change?

**Comment by amosr** [comment]
no, I think it's best to just change the parser for "feature".

I'd rather not modify the lexer, because I like to keep the "Constructor" and "variable" distinction in case statements, so it's a little more obvious what is a catch-all variable, and what is a misspelt constructor

```
case foo
  | Nonez  -> 0
  | Some x -> x + 1
```
if variable & constructors were lumped together, this would be fine, although maybe the overlap check would notice that one..

**Pull request closed without merging**
