### PR TITLE
Replace time/date

### PR DESCRIPTION
**Pull request by tranma**
replace the combo of `time` and `dates` libraries with `thyme`. It should build on 7.10 now?

### CODE REVIEW

**Comment by amosr** [comment]
perhaps we could actually use Delorean for this, instead?

**Comment by tranma** [comment]
this is so far behind, does it still apply? in any case the `dates` library should really be replaced

**Comment by markhibberd** [comment]
:+1: For thyme. Don't think delorean really captures the right type of thing.

**Comment by amosr** [comment]
yep, if you want to do this go for it. if you don't want to, it can certainly wait. @HuwCampbell is touching this date stuff right now though, so it might be worth throwing away this branch and starting again

**Comment by nhibberd** [comment]
@amosr @HuwCampbell @tranma Is this still relevant?

**Comment by amosr** [comment]
@nhibberd nah I think I'll just delete it

**Pull request closed without merging**
