### PR TITLE
Temporality constraints can be strict

### PR DESCRIPTION
**Pull request by tranma**
In Source, our constraints on `Temporality` are more like sub-typing, i.e.

```
  requireTemporality ty tmp
   | (tmp',_,_) <- decomposeT ty
   = case tmp' of
      Just TemporalityPure -> return []
      Nothing              -> return []
      Just tmp''
       -> return $ require a (CEquals tmp'' tmp)
```

This is fine, but it means we have more programs to cover unnecessarily in ToCore. I think we can just add a `requireTemporalityStrict` where `ty` must have a temporality exactly as required. This can be used for things like `GroupBy` keys (see the diff).

I'm happy to consider other solutions if there are better ways.

### CODE REVIEW

**Comment by tranma** [comment]
! @amosr

**Comment by amosr** [comment]
hmm, so what's the benefit of this? that something like
```
filter True
group 5
```
will be outlawed?

I think I need more context - what is this trying to solve?

**Comment by tranma** [comment]
@amosr trying to outlaw expressions like `group True ~> ...`

**Comment by tranma** [comment]
hm, on second thought, I think this isn't right after all. There should be no reason why the sub-typing relation isn't appropriate.

**Comment by tranma** [comment]
yeah, this is wrong.
I was having problems with expressions like `group .. ~> box (Some None)` where conversion to Core failed, but that's a problem with the conversion, not with the Source. Nvm this change

**Pull request closed without merging**
