### PR TITLE
fix 7.10 build

### PR DESCRIPTION
**Pull request by tranma**
I'm not sure why we don't see these errors on 7.8?

@jystic

### CODE REVIEW

**Comment by jystic** [comment]
Ok with this if we put bangs on all the data types that are deriving `NFData` so that `seq` is the same as `deepseq`

**Comment by olorin** [comment]
> I'm not sure why we don't see these errors on 7.8?

https://ghc.haskell.org/trac/ghc/wiki/Migration/7.10#deepseq-1.4.0.0deepseq-1.4.1.0

**Comment by jystic** [comment]
Maybe it's better to make everything strict and do:
```
instance NFData Foo where rnf x = seq x ()
```
instead of `deriving Generic`, at least it's guaranteed to be the same.

**Comment by tranma** [comment]
yeah, I'm leaning towards removing derive Generic completely. Don't want to make the AST too strict

**Comment by jystic** [comment]
```hs
class MFData where
  mediumSeq :: a -> b -> b
```

**Comment by tranma** [comment]
`($!.)` instead of `($!!)`?

**Comment by tranma** [comment]
it's half a bang

**Comment by jystic** [comment]
or `($!?)`

it's unknown how much more than whnf we seq'd

**Comment by amosr** [comment]
does `($¡)` work?

**Comment by tranma** [comment]
should I change all the NFData and `$!!` to MedData and `$?!`?

**Comment by tranma** [comment]
tested this with `ice` on our Big Data Case (tm).
Compilation time is about the same. Space wise, looks like it used a bit more memory than before, but still made it until the GC cleared up some 30GB, so that's still ok.

**Comment by jystic** [comment]
Looks good to me ✌️

**Pull request merged**
