### PR TITLE
skip_to_next_entity bug

### PR DESCRIPTION
**Pull request by tranma**
skip_to_next_entity marks part of the input buffer as skipped (by setting state->input_ptr), but this needs to be reset before each read_whole_buffer.

we didn't encounter this before because we didn't test with big data so the input always fit into the read buffer, even when some of it is skipped.

! @amosr @jystic

### CODE REVIEW

**Comment by erikd-ambiata** [comment]
Well done! Is it possible to write a test for this?

**Comment by tranma** [comment]
yeah, perhaps we should make the buffer sizes configurable, and run quickcheck with random sizes

**Comment by erikd-ambiata** [comment]
@tranma    `s/perhaps//`

**Comment by amosr** [comment]
super 🗳

**Pull request merged**
