### PR TITLE
Off-by-one in mean fold

### PR DESCRIPTION
**Pull request by olorin**
Could be misreading (not sure how to actually run the thing), but

```
(v_, 1) : case s | (m, n) -> (m + (v_ - m) / (n + 1), n + 1)
```

Input: [5]
Initial case: (5, 1)
Output: 0 + (5 - 0) / (1 + 1), 1 + 1 = 2.5

/cc @jystic @amosr

### CODE REVIEW

**Comment by tranma** [comment]
I think the current code is right, just need to start at 0 rather than 1.

**Comment by tranma** [comment]
(see the online variance algorithm below this)

**Comment by amosr** [comment]
ah. I think this is right, but I agree it's confusing. the ":" in the fold means "followed by" or "then", so it will only be executed for the second input (or first input if it were fold instead of fold1)

So in this case the value of the fold ``s`` is (5,1), then it just extracts the first part afterwards.
For a two-element input

```
[5, 2]

fold1 s = (_v, 1) : case s | (m, n) -> (m + (v_ - m) / (n + 1), n + 1)
==>
fold1 s = (5, 1) : case s | (m, n) -> (m + (v_ - m) / (n + 1), n + 1)
==>
fold1 s = case (5,1) | (m, n) -> (m + (v_ - m) / (n + 1), n + 1)
==>
fold1 s = (2 + (5 - 2) / (1 + 1), 1 + 1)
==>
fold1 s = (3.5, 2)
```

**Comment by olorin** [comment]
Yep, figured out how to run stuff, current code is indeed correct. :+1:

**Pull request closed without merging**
