### PR TITLE
Use the annotated pretty printer

### PR DESCRIPTION
**Pull request by HuwCampbell**
Just keeping this simple for now, subtle additional annotations can be added later.

### CODE REVIEW

**Comment by tranma** [comment]
what does this do?

**Comment by amosr** [comment]
woohoo! :pray:

**Comment by amosr** [comment]
I think you'll need to update the tests.
```
$ test/cli/repl/run
# eyeball the differences. probably only escape codes
$ test/cli/repl/run UPDATE
```

**Comment by tranma** [comment]
I do `git add -p` afterwards and :eyes: each chunk really hard

**Comment by amosr** [comment]
that's probably a lot easier to read...

**Comment by jystic** [comment]
:dromedary_camel: nice :)

**Comment by HuwCampbell** [comment]
Yep, done.
I removed one of the annotation, as it was too high up, and the current reset function doesn't pop, but rather resets completely, so it was a bit ugly.

**Pull request merged**
