### PR TITLE
Avalanche type checker: require fresh names. Freshen after flattening.

### PR DESCRIPTION
**Pull request by amosr**
! @tranma @jystic

### CODE REVIEW

**Comment by amosr** [comment]
This changes the typechecker to require fresh names

**Comment by tranma** [comment]
this seems legit
👍

**Comment by tranma** [comment]
but you might need to freshen after something else as well, not just flatten.

**Comment by amosr** [comment]
Yeah, I'm worried about whether I'll be able to get them all, but on the other hand I think it's better to leave it as an error so we can actually find these places

**Comment by amosr** [comment]
ergm

**Pull request merged**
