### PR TITLE
prop_seaworthy (no psv)

### PR DESCRIPTION
**Pull request by tranma**
not there yet, we still get errors like `compute function #0 - eval:3:5: error: unknown type name 'ibuf_t__ibuf_t__idate_t'; did you mean 'iarray_t__ibuf_t__idate_t'?`

### CODE REVIEW

**Comment by amosr** [comment]
ah, yeah. so the problem is that you can describe programs with nested buffers and unboundedly nested arrays in Core, but not in Source. @jystic's psv test filters out the bad types

**Comment by tranma** [comment]
cool, maybe I can just modify Core Arbitrary?

**Comment by amosr** [comment]
I think maybe he has a "WellTypedAvalanche" or something with a nice arbitrary instance

**Comment by tranma** [comment]
just like prop_psv without the psv now

**Comment by amosr** [comment]
:+1:

**Pull request merged**
