### PR TITLE
Fix SeaOutputTypeMismatch test failure

### PR DESCRIPTION
**Pull request by jystic**
! @tranma

### CODE REVIEW

**Comment by tranma** [comment]
could you change the comment `--^ types of arguments` to `--^ unmelted types of arguments`?

**Comment by jystic** [comment]
> could you change the comment `--^ types of arguments` to `--^ unmelted types of arguments`? 

done

**Comment by tranma** [comment]
makes sense now
👍

**Comment by tranma** [comment]
if only `Melted` and `Unmelted` were different types lol

**Pull request merged**
