### PR TITLE
Upgrade mafia

### PR DESCRIPTION
**Pull request by jystic**

### CODE REVIEW

**Comment by jystic** [comment]
Damn travis, why aren't the profiling libraries for base installed, how is that even possible??

**Comment by jystic** [comment]
ugh, just about done with travis:
```
Disallowing packages: ghc-7.8.4-prof
If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
```

**Comment by domdere** [comment]
nobody profiles

**Comment by olorin** [comment]
I always used stack GHC with travis builds, seemed like the least-painful option.

**Comment by jystic** [comment]
@olorin cool, got an example?

heh cabal+mafia+stack is *all* you need!

**Comment by olorin** [comment]
@jystic https://github.com/anchor/oauth2-server/blob/master/.travis.yml

**Comment by olorin** [comment]
(That's using stack for the build, but can just run `stack setup` and then munge the path before running `mafia`.)

**Comment by jystic** [comment]
Yay, it works! /cc @tranma @amosr

**Comment by tranma** [comment]
cool! I can just use mafia in this https://github.com/ambiata/icicle/pull/283, yeah?
:100: :100:

**Comment by jystic** [comment]
@tranma yeah!

**Pull request merged**
