### PR TITLE
nested structs

### PR DESCRIPTION
**Pull request by tranma**
This is useful especially for dense psv input.

Example:

```
[fact.test]
  encoding="(foo:(fizz:int,buzz:string),bar:int)"
```

```
homer|test|{"foo":{"fizz":1,"buzz":"huh"},"bar":0}|1999-01-01
homer|test|{"foo":{"fizz":5,"buzz":"huh"},"bar":1}|1999-01-02
homer|test|{"foo":{"fizz":3,"buzz":"huh"},"bar":1}|1999-01-03
homer|test|{"foo":{"fizz":3,"buzz":"heh"},"bar":0}|1999-01-04
```

```
> feature test ~> group foo.buzz ~> max foo.fizz
- Core evaluation:
[homer, [("heh",3),("huh",5)]]
```

might need some cli tetsts

/cc @amosr

### CODE REVIEW

**Comment by tranma** [comment]
works for both dense and sparse input (see ice CLI tests)

**Comment by jystic** [comment]
Might be good to update the tests so they have a nested struct?

Otherwise, all good :diamonds:

**Comment by tranma** [comment]
@jystic yeah, I knew I forgot something!

**Comment by tranma** [comment]
@jystic check out t18-nested-structs!

**Comment by jystic** [comment]
:money_with_wings:

**Pull request merged**
