### PR TITLE
Use C "dictionary" in icicle-bench

### PR DESCRIPTION
**Pull request by tranma**
lets you supply a C source file instead of a dictionary:

```
./dist/build/icicle-bench/icicle-bench --source dictionary\
--dictionary test/cli/bench/t4-dictionary.toml\
--input test/cli/bench/t4-in.psv\
--output out1\
--code t4.c\
--snapshot-date 2017-1-1

./dist/build/icicle-bench/icicle-bench --source c\
--input test/cli/bench/t4-in.psv\
--output out1\
--code t4.c\
--snapshot-date 2017-1-1

diff -u out1 out2                                                                                                                                                                                                                                                              
```

! @jystic @amosr

### CODE REVIEW

**Comment by jystic** [comment]
Awesome!

Hmm the command line flags are bit confusing now I think (having --code for input and output), maybe we should have something like:
```
icicle-bench
(--input-dictionary test/cli/bench/t4-dictionary.toml | --input-code t4.c)
--input test/cli/bench/t4-in.psv
--output out1
[--output-code t4.c]   <- now optional?
--snapshot-date 2017-1-1
``

**Comment by tranma** [comment]
maybe. can you have mutually exclusive optparse options easily? (i.e. `(--dictionary STRING | --csrc STRING)`) -- or just check the command yourself? If it's the latter, I suppose `(--source ARG) [--dictionary STR] [--csrc STR] [--c-output STR]` isn't too confusing.

**Comment by jystic** [comment]
> maybe. can you have mutually exclusive optparse options easily? (i.e. (--dictionary STRING | --csrc STRING)) -- or just check the command yourself?

yeah this works really well actually, using it in [blizzard](https://github.com/ambiata/blizzard/blob/master/blizzard-cli/main/zz.hs#L163-L166) for `(--snapshot-data DATE | --chord CHORD_URL)`

**Comment by tranma** [comment]
wow that's rather unexpected

**Comment by jystic** [comment]
:100: This is brilliant!

**Pull request merged**
