### PR TITLE
Allow unlimited number of facts per entity

### PR DESCRIPTION
**Pull request by tranma**
Just what it says on the tin. That was silly to begin with... Turns out users don't usually set the limit.

! @amosr

### CODE REVIEW

**Comment by jystic** [comment]
Don't we usually want a limit though? (maybe I missed something last week)

**Comment by markhibberd** [comment]
I don't understand this either, there needs to be a limit unless I am missing something obvious.

**Comment by tranma** [comment]
There still can be a limit, the user just needs to set it explicitly in ice/icicle-bench. Currently if nothing is provided, icicle uses 1024*1024 per entity, which is very low. (I saw several entities exceeding this limit)

**Comment by tranma** [comment]
Having an `Unlimited` option is still good I think, I can just make `Limited 1million` the default again if that's preferred

**Comment by markhibberd** [comment]
Maybe the limit is a bit low, (but I am not sure that a million facts in 2 years should be common unless there is an issue that we are missing elsewhere). But there should always be a limit, it should be safe and predictable by default and we can choose to lift limit if we hit it.

**Comment by tranma** [comment]
Ack, the default will still be 1 million then.

**Comment by markhibberd** [comment]
As long as prod will _never_ run with unlimited by accident.

**Comment by jystic** [comment]
We decided this isn't worth it, will revisit if necessary

**Pull request closed without merging**
