### PR TITLE
Bring icicle's map output closer to ivory's.

### PR DESCRIPTION
**Pull request by HuwCampbell**
So this is a bit unfortunate, Ivory outputs what appears to be a json struct for map encodings (group bys and the like).
This isn't really that safe though unfortunately, and we lose quite a bit of type information. It does however make things more consistent down the line if both projects do the same thing.

### CODE REVIEW

**Comment by tranma** [comment]
so it will always say "null" for tombstones inside a map?

**Comment by HuwCampbell** [comment]
There's a guard above to ensure tombstone's aren't written out as the key.

**Comment by amosr** [comment]
this looks good to me. :peach:
it doesn't seem to me that we lose that much type information, but I might be misunderstanding. could you elaborate?

**Comment by HuwCampbell** [comment]
Just that for the keys, everything goes to String.

**Comment by amosr** [comment]
oh right, ok. yeah maybe just put a caveat in the comments there. I like comments.
I guess we require this to be true:
```
forall (x y : A).
     show x == show y
 ==> x == y
```
which seems reasonable to me

**Comment by HuwCampbell** [comment]
An alternative could be to have a struct with:
{"k":null, "v":null}
And push the other direction for consistency.

**Comment by amosr** [comment]
I don't mind either way. keeping it as a proper key seems useful if one were to use it as json. I think strange things are fine (and necessary) but we just need to clearly document the rationale and the implications

**Comment by HuwCampbell** [comment]
Ok, let's go with this version.

**Comment by amosr** [comment]
:apple:

**Pull request merged**
