### PR TITLE
nan it all to hell

### PR DESCRIPTION
**Pull request by amosr**
I decided to move NanEq into icicle-data, because alpha equality, which is defined in icicle-data needed to use it.

! @jystic @tranma 
/jury approved @jystic

### CODE REVIEW

**Comment by tranma** [comment]
wow a new notion of alpha equivalence

**Comment by amosr** [comment]
I think I've used this pun before.
I also changed the Map type generator, so it would only generate Ord types or primitives. Basically no arrays or maps inside the key of a Map.

**Comment by amosr** [comment]
#625

**Comment by jystic** [comment]
👍

**Pull request merged**
