### PR TITLE
Topic/window frames

### PR DESCRIPTION
**Pull request by HuwCampbell**
WIP.
Avalanche hasn't changed yet, but it's worth a look.

### CODE REVIEW

**Comment by tranma** [comment]
if I remember correctly, these are windows with access to one previous element..?

**Comment by HuwCampbell** [comment]
That's right

**Comment by tranma** [comment]
oh, now I get it, "frames" around a window.

**Comment by HuwCampbell** [comment]
So there's a few things still needing to be done here and I wouldn't mind chatting about them.

Firstly: avalanche isn't implementing this.

Secondly: I'm not sure what to do with the date of the feature which is seen "at the window frame". There's no need to know when said feature was dropped, and (because "now" is an aggregate feature) it's not possible to easily know the window's edge without exposing bubblegum filtering issues. On the other hand, fudging the date such that it is at the edge of the window could be dangerous.

Thirdly: if a feature is tombstoned out before the start of the frame, we will see that tombstone, but if there was just no fact written, we won't see anything until inside the window. My intuition is that these two scenarios should give the same result, but here they probably won't.

**Comment by amosr** [comment]
(2)

it seems like, depending on the query, you'd actually want to know both the date of the outside fact, as well as the frame date.
for example, if you were doing a gradient or integral might you want to interpolate between the outside value and the first inside value to get the value at start of frame?

you're right, I don't know whether the "start window" date would be useful as an aggregate, it seems a bit unwieldy. the bubblegum filtering could be dealt with by putting everything in the window in the bubblegum. that is, any predicate filters would filter out the values, but leave the bubblegums in.

**Comment by tranma** [comment]
what's happening with this?

**Comment by amosr** [comment]
if you can update the last previous date to be the edge of the window, and add Avalanche evaluation, I'd be happy for this to be merged

**Comment by amosr** [comment]
this is related to #82. this will be good eventually but closing for now

**Pull request closed without merging**
