### PR TITLE
Add new Prelude function to compute mode of stream

### PR DESCRIPTION
**Pull request by amosr**
```
# Group by given key, count, and find the most common element.
# If there are multiple elements with the maximum count we return one of those,
# but exactly which one is undefined and deterministic.
mode key
 = group fold (key', count') = (group key ~> count key)
 ~> max_by count' key'.

mode : Element a -> Aggregate Possibly a.
```

### CODE REVIEW

**Comment by tranma** [comment]
hm, why is this the "mode" of stream?

**Comment by amosr** [comment]
I think it's a common statistics term, though maybe it isn't a good name given our use of mode-al types

https://en.wikipedia.org/wiki/Mode_(statistics)

**Comment by erikd-ambiata** [comment]
Not a blocker, but is it possible to write code to update the `test/.../expected` files at test time so they don't need to be checked into the repo? This would drasitcally reduce the noise in commits like this.

**Comment by amosr** [comment]
it would probably be easier to just remove the "ok, loaded N functions" statement.
I might be misunderstanding, but the expected files are checked against each the actual test output: lazy testing with diff

**Comment by tranma** [comment]
@amosr ah right, I did indeed think it had something to do with our modal types, was very confused :) Maybe call it distribution_mode, or probablity_mode, or something?

**Comment by amosr** [comment]
yep, good plan. will rename. and change the example to be a bit better (it should be dividing by 10,000 instead of 1,000)

**Comment by amosr** [comment]
renamed… @tranma

**Comment by jystic** [comment]
I'm fairly sure your average Icicle user won't be versed in modal types and would expect `mean`, `median` and `mode` to be statistical functions. The name `mode` might be confusing for us, but we're not the target audience.

/cc @blever @markhibberd

**Comment by amosr** [comment]
that is true. but does is hurt the average user to have a slightly longer name?

**Comment by tranma** [comment]
💯 for distribution_mode

**Comment by jystic** [comment]
Do you have something in mind that you would prefer to save `mode` for?

I think `mode` is better, but I don't really mind, so if you two feel strongly the other way then go ahead 👍

**Comment by markhibberd** [comment]
> does is hurt the average user to have a slightly longer name?

I think it does when it is replacing a standard term from their domain with something else. I am very much on the side of using "mode", happy to talk about it, but we need to do a sanity check on the prelude etc... before we put this in hands of users anyway, so it isn't something we can't fix/change mind on (yet).

**Comment by amosr** [comment]
ok, good point. `mode` it is

**Pull request closed without merging**
