### PR TITLE
Safe substitution on Source expressions. Fix substitution.

### PR DESCRIPTION
**Pull request by amosr**

### CODE REVIEW

**Comment by tranma** [comment]
does this fix https://github.com/ambiata/icicle/issues/138?

**Comment by amosr** [comment]
@tranma not yet, but it is the first step to implementing it. I will add an option to `inlineTransform` which is whether to add lets or substitute directly, which should be fairly simple to do

**Comment by jystic** [comment]
😋 looks good

**Comment by amosr** [comment]
will merge & implement inlineTransform change as separate PR

**Comment by tranma** [comment]
wow so this substitution code works first try, great job @amosr 👍 👏 👏 👏

**Comment by jystic** [comment]
💯

**Pull request merged**
