### PR TITLE
travis

### PR DESCRIPTION
**Pull request by tranma**
so professional, wow.

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
failing to clone orphanarium, it was renamed to disorder

**Comment by tranma** [comment]
but github/ambiata/orphanarium redirects to disorder.hs, right?

**Comment by tmcgilchrist** [comment]
It does but I don't think a git clone of orphanarium works by the look of the travis logs.

```
Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:ambiata/orphanarium' into submodule path 'lib/orphanarium' failed
The command "eval git submodule update" failed. Retrying, 2 of 3.
```

**Comment by tranma** [comment]
hm, it could still clone locally when I tried (after the name change) though, I'll check.

**Comment by tranma** [comment]
yeah, still works locally:

```
git submodule update
Cloning into 'lib/orphanarium'...
remote: Counting objects: 518, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 518 (delta 2), reused 0 (delta 0), pack-reused 501
Receiving objects: 100% (518/518), 64.69 KiB | 0 bytes/s, done.
Resolving deltas: 100% (161/161), done.
Checking connectivity... done.
Submodule path 'lib/orphanarium': checked out '11041d934f32547a1480d2209c9a73ecb9394dc7'
```

**Comment by tranma** [comment]
done @amosr

**Comment by amosr** [comment]
:hibiscus:

**Comment by amosr** [comment]
:higgs_boson:

**Pull request merged**
