### PR TITLE
Split out icicle-repl & Add icicle-repl-source

### PR DESCRIPTION
**Pull request by tranma**
The `icicle-repl-source` REPL only typechecks Source expressions, which should fit the use case in https://github.com/ambiata/icicle/issues/424

@amosr @jystic

### CODE REVIEW

**Comment by tranma** [comment]
packages so far

- `icicle-data`: common
- `icicle-source`: source, encoding
- `icicle-core`: core defs and transforms
- `icicle-compiler`: rest of the blob
- `icicle-repl-data`: common repl bits, mostly terminal fiddling
- `icicle-repl-source`: source repl
- `icicle-repl`: same old repl

**Comment by amosr** [comment]
looks groovy 💃

**Comment by jystic** [comment]
wondering if we need the `icicle-repl-source` executable? reading https://github.com/ambiata/icicle/issues/424 it seems as though @markhibberd just needs a library? /notsure

**Comment by tranma** [comment]
yeh a library is probably enough, but a REPL might make it easier esp. if they want to use it in scripts /notsure
happy to remove it if Mark only needs a library

**Comment by jystic** [comment]
I don't mind, although better to have less code if we can manage it I reckon

**Comment by tranma** [comment]
removed the source REPL for now

**Pull request merged**
